# Python, Numpy and Matrix Algebra: Brief Introduction

(by Chenkuan Liu)

### 1. Python

Python is a programming language that is widely used today. Among all of its characteristics, there are two of them that make Python such a popular programming language.

1) Ease of coding

Python is a high-level programming language that has done a lot of stuff automatically for you, so it becomes much easier and faster to write code in Python compared to other languages. Take the most common example, here is the first thing you would write when you learn a new programming language:

In [1]:
print("Hello World!")

Hello World!


Note that it only requires one line for Python to do this. In contrast, in other languages like C, C++, Java and others, it requires several lines to import appropriate interfaces or initialize public classes to do this. The ease of code writing makes Python popular.

2) Variety of packages

Python contains numerous packages written by developers across the world that you can import from. These packages serve different purposes and they allow you to perform tasks in mathematics, statistics, electrical engineering, computer science, data science, software engineering, scientific computing, artificial intelligence, game development and many other fields. It is such diversity of available packages that makes Python stand out.

### 2. NumPy

NumPy is one package in Python that specifically deals with vectors, matrices and multidimensional arrays. It is very useful in computational engineering and scientific computing. After installation, the typical way to import NumPy is:

In [2]:
import numpy as np

We normally use "np" for its abbreviation. Next, we will use its built-in fuctions to perform vector and matrix operations.

1) Creating Numpy Arrays

Creating Numpy Array is simple. For instance, if you want to create a vector [2,4,6,8,10], then you just need to type:

In [3]:
a = np.array([2,4,6,8,10])

The np.array() command will take your input and return a numpy array. Specifically, you can print it out to check its value and its data type.

In [4]:
print(a)
print(type(a))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


We see that it belongs to the class 'numpy.ndarray'. Note that, if you have learned Python before, you might see that the initialization of numpy array is very similar to the creation of lists. But, they are in fact different data types. We can check it below:

In [5]:
ls = [2,4,6,8,10]
print(ls)
print(type(ls))

[2, 4, 6, 8, 10]
<class 'list'>


You can see that, though looks similar, the initialized "ls" here belongs to the class 'list'. It is important not to mix them up during your execution.

Similarly, creating a matrix simply means creating a multidimensional numpy array:

In [6]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that you need extra square brackets and commas to create a matrix. The numpy operation of matrices will be discussed in the future.

2) Arithmetic operation

NumPy has overwritten the common arithmetic operators. So, to add, substract, multiply, or divide arrays, you just need to use the "+", "-", "\*", "/" operators (More will be discussed later regarding multiplications and divisions, which has some special maneuvering that needs to pay attention to).  

For addition and substraction, let's look at some basic examples:

In [7]:
v1 = np.array([1,2,3])
v2 = np.array([2,4,6])
v_add = v1 + v2
v_sub = v1 - v2
print("v_add:", v_add)
print("v_sub:", v_sub)

v_add: [3 6 9]
v_sub: [-1 -2 -3]


We see that plus and minus signs will automatically perform elementwise addition and substraction.

In addition, we use "\*\*" to calculate the elementwise power of a vector. (elementwise power is seldom used alone, so here is only for demonstration purpose)

In [8]:
v1_square = v1**2
print("v1_squre:", v1_square)

v1_squre: [1 4 9]


Now, what if we multiply them or divide them?

In [9]:
print(v1 * v2)
print(v1 / v2)

[ 2  8 18]
[0.5 0.5 0.5]


We see that multiplication and division are still performed elementwise. However, for most of the time, we are not interested in vector division. And, for multiplication, we are mostly interested in the inner product of two vectors rather than their elementwise multiplication. To do that, we will call an additional function: np.dot():

In [10]:
print(np.dot(v1, v2))

28


we can observe that np.dot() takes two vectors as input and outputs a scalar which is their inner product.

3) Norm

Norm is a concept that is widely used in mathematics and scitific computing. It can actually become very complex. But, without digging too much, we only consider the Euclidean norm at here (which is actually $L_2$ norm in formal speaking). A simple way to consider Euclidean norm of a vector is to view it as the distance from the vector to the origin. Specifically, taking an n-dimensional array

$$\textbf{v}=\begin{bmatrix}
           v_{1} \\
           v_{2} \\
           \vdots \\
           v_{n}
         \end{bmatrix},$$ 

its Euclidean norm is

$$\begin{equation}\text{norm}\textbf{(v)}=\sqrt{\sum\limits_{1}^{n} v_{i}^{2}}=\sqrt{v_{1}^{2} + v_{2}^{2} + \cdots +v_{n}^{2}}\end{equation}.$$

$$\sqrt{\sum_{i=1}^{n} v_{i}^{2}} = \sqrt{v_{1}^{2} + v_{2}^{2} + \cdots +v_{n}^{2}}.$$
$$\sqrt{\sum_{i=1}^{n} v_{i}^{2}}$$
$$\sqrt{v_{1}^{2} + v_{2}^{2} + \cdots +v_{n}^{2}}.$$
$$\sqrt{v_{1}^{2}}$$

$$\begin{equation}\text{norm}\textbf{(v)}=\sqrt{\sum\limits_{1}^{n} v_{i}^{2}}=\sqrt{v_{1}^{2} + v_{2}^{2} + \cdots +v_{n}^{2}}\end{equation}.$$

$$\sqrt{\sum_{i=1}^{n} v_{i}^{2}} = \sqrt{v_{1}^{2} + v_{2}^{2} + \cdots +v_{n}^{2}}.$$
$$\sqrt{\sum_{i=1}^{n} v_{i}^{2}}$$
$$\sqrt{v_{1}^{2} + v_{2}^{2} + \cdots +v_{n}^{2}}.$$
$$\sqrt{v_{1}^{2}}$$

Though calculating a Euclidean norm takes several steps, in numpy, we can handle this in a single command:

In [11]:
v = [3,4,12]
v_norm = np.linalg.norm(v)
print(v_norm)

13.0


You can check that this is the correct norm. Specifically, we use np.linalg.norm() function to compute its norm ("linalg" stands for linear algebra here).

### 3. Bring it Together: a Toy Example

The sections above only introduced basic commands and fuctions in numpy. However, with them at hand, we can already perform some interesting stuff and gain new perspectives from the knowledge of linear algebra.

<img src="cube.png" style="width:400px;height:300px"/>

Take the cube above for example, suppose that the cude has side length 1. A high school geometry problem would ask that what is the degree of the angle $\angle{FAG}$. The answer would be $60^\circ$, since if you connect GF, AFG would form an equilateral triangle with side length $\sqrt{2}$, which means that $\angle{FAG} = 60^\circ$.

But now, since you have started the journey of linear algebra, you can approach the problem in a more interesting way. You can put it in a 3D coordinate system, and it will look like this:

<img src="cube2.png" style="width:400px;height:300px"/>

After viewing it inside the coordinate system, we can get the coordinates of point A,F,G respectively, which are labeled above. Now, we can use the formula $$cos(\theta) = \frac{\bf{v_1} \cdot \bf{v_2}}{\Vert\bf{v_1}\Vert \Vert\bf{v_2}\Vert}$$ to compute the angle between the two vectors $\bf{v_1}$ and $\bf{v_2}$, which are $\overrightarrow{AF}$ and $\overrightarrow{AG}$ respectively. 

To demonstrate the power of numpy, we can write a generalized function to compute the angle between any two vectors with what we have presented above:

In [14]:
def get_angle(v1, v2):
    """
    Arguments: 
    v1 -- the first input vector in numpy array
    v2 -- the second input vector in numpy array
    
    Returns:
    theta -- the degree of the angle between v1 and v2
    """
    nominator = np.dot(v1,v2)    # compute nominator as above
    denominator = np.linalg.norm(v1) * np.linalg.norm(v2)    # compute denominator as above
    radian = np.arccos(nominator/denominator)    # divide and calculate theta,
                                                 # note that np.arccos() returns radian value
    theta = np.degrees(radian).round()    # convert into degree value and perform rounding
    return theta

Now let's try it out with the example above:

In [15]:
v1 = np.array([0,1,1])
v2 = np.array([1,0,1])
theta = get_angle(v1, v2)
print("The degree between v1 and v2 is:", theta)

The degree between v1 and v2 is: 60.0


Now we see that with the knowledge of basic numpy commands and vector operations, we can compute the angle between any two vectors. Note that when the dimension of vectors gets larger than three, it would become hard to visualize geometrically, and that's when linear algebra kicks in and does the job :)

### Extras

- The official website of Numpy is https://numpy.org/. You can search for a lot of numpy functions and their descriptions over there.
- There are many tutorials to get into Jupyter notebook, the one I find that might be helpful is on https://www.dataquest.io/blog/jupyter-notebook-tutorial/.
- There is also a book called Matrix Cookbook, which is available [online](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf). It is more like a dictionary of matrix operations that you can refer to. Some of the materials inside are covered in our lecture, but most of them are beyond the scope of this class. If you are interested, you can have a look of it.